networks:
  appnet:
    external: true

services:
  php-rms:
    container_name: php-ci4-rms
    build:
      context: .
      args:
        APP_ENV: prod
    restart: always
    networks:
      - appnet
    environment:
      CI_ENVIRONMENT: production